### ISSUE TITLE
Redirect dataset accession number

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1176]
Tracking ticket for recording datasets that need to be: redirected, DOI changed, and curator note

- [ ] The author needed to reupload with defaced images, but in the publication had cited the previous DS number: 1988. **2/15: waiting on DS owner**. This is regarding [DS1996](https://openneuro.org/datasets/ds001996/versions/1.0.0) redirecting from DS1988 (now deleted but referenced in the publication). ~~May it be possible to redirect this dataset to DS 1988 to align with the publication? (The publishers cannot change the article due to editor rules)~~

- [x] another dataset with this issue of differing association number than reported in paper - https://openneuro.org/datasets/ds002149 but paper reports https://openneuro.org/datasets/ds002078 (**2/19: redirect and DOI confirmed**) (3/6: former dataset accession in README by dataset owner)

- [x] https://openneuro.org/datasets/ds002250 redirect from https://openneuro.org/datasets/ds002222 [that dataset is now deleted but was referenced in the paper] (RB: no 2222 DOI's were found)

- [X]  https://openneuro.org/datasets/ds002345 redirect from https://openneuro.org/datasets/ds002245 [that dataset is now deleted but referenced online] (**2/18: redirect and DOI confirmed**) 

- [x] https://openneuro.org/datasets/ds002171 to https://openneuro.org/datasets/ds002380 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds002068 to https://openneuro.org/datasets/ds002543 (3/6: curator note added to dataset page, made new snapshot)

- [x]  https://openneuro.org/datasets/ds001750 to https://openneuro.org/datasets/ds002550

- [x] https://openneuro.org/datasets/ds001851 to https://openneuro.org/datasets/ds002574 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds002036 to https://openneuro.org/datasets/ds002596 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds002317 to https://openneuro.org/datasets/ds002602 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds001900 to https://openneuro.org/datasets/ds002608 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds002319 to https://openneuro.org/datasets/ds002609 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds002337 to https://openneuro.org/datasets/ds002606 (3/6: curator note added to dataset page, made new snapshot)

- [x] https://openneuro.org/datasets/ds001782 to https://openneuro.org/datasets/ds002614 (3/13: curator note added to dataset page)

- [x] https://openneuro.org/datasets/ds002572 to https://openneuro.org/datasets/ds002647 (3/20: curator note added to dataset page) 

- [x] https://openneuro.org/datasets/ds002070 to https://openneuro.org/datasets/ds002711 

- [x] https://openneuro.org/datasets/ds001985 to https://openneuro.org/datasets/ds002712

- [x] https://openneuro.org/datasets/ds002653 to https://openneuro.org/datasets/ds002728

- [x] https://openneuro.org/datasets/ds001165 to https://openneuro.org/datasets/ds002750

- [x] https://openneuro.org/datasets/ds001393 to https://openneuro.org/datasets/ds002738

- [x] https://openneuro.org/datasets/ds001219 to https://openneuro.org/datasets/ds002734

- [x] https://openneuro.org/datasets/ds001934 to https://openneuro.org/datasets/ds002727

**Comment by effigies** [comment]
Thinking of the long-term strategies, it seems to me that changing accession numbers would have a lot of moving parts, a lot of chances to go wrong, and probably require manual intervention. On the other hand, redirecting URLs/DOIs to a superseding dataset seems like a much lighter-weight solution. Or a banner, similar to what was discussed in #1136, but applying to a whole dataset instead of a single snapshot.

WDYT?

**Comment by franklin-feingold** [comment]
I agree - my hope is that this case is rare. I think redirecting sounds good!

**Comment by franklin-feingold** [comment]
closing this - list of redirects can be found: https://github.com/OpenNeuroOrg/openneuro/blob/master/packages/openneuro-app/src/scripts/errors/errorBoundary.jsx
