### ISSUE TITLE
Google reported issues

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1268]
This ticket captures all the various Google Search Console errors flagged since August 29, 2019.

**Comment by ckrountree** [comment]
- [ ] Google mobility shows an error for this dataset:  **(MOBILE)** https://openneuro.org/datasets/ds002041/versions/1.1.0/file-display/task-TD_events.json

**ds000244** - (9/8 detected)  https://openneuro.org/datasets/ds000244 **(MOBILE)**
- [ ] content wider than screen
- [ ] clickable elements too close together
- [ ] Viewport not set (reported file: https://openneuro.org/crn/datasets/ds000224/snapshots/00001/files/T1w_group.html and https://openneuro.org/crn/datasets/ds000224/snapshots/00002/files/T1w_group.html)
- [ ] Text too small to read (reported file: https://openneuro.org/crn/datasets/ds000224/snapshots/00001/files/T1w_group.html and https://openneuro.org/crn/datasets/ds000224/snapshots/00002/files/T1w_group.html)

**[ds001928](https://openneuro.org/datasets/ds001928/versions/1.1.0)** - (10/18 detected) flagged for the participants.tsv file display **(MOBILE)**
- [ ] content wider than screen
- [ ] clickable elements too close together  

**Text too small** - (8/20/20 latest detected; 11/6 first detected) **(MOBILE)**
ds001784, ds000201, ds001506, ds000117, ds002232, ds000221, ds000256, ds000030, ds000140, ds000223

**Clickable elements too close together** - (3/4/20 detected) **(MOBILE)**
ds000140 (README)
ds002653 (participants.json)
(11/5/20 reported files: https://openneuro.org/datasets/ds003346/versions/1.1.0/file-display/participants.tsv, https://openneuro.org/datasets/ds002134/versions/1.0.0/file-display/participants.json, https://openneuro.org/datasets/ds003114/versions/1.0.1/file-display/participants.json, https://openneuro.org/datasets/ds002411/versions/1.1.0/file-display/participants.json, https://openneuro.org/datasets/ds002738/versions/1.0.1/file-display/task-reward_events.json, https://openneuro.org/datasets/ds002940/versions/1.0.1/file-display/participants.json, https://openneuro.org/datasets/ds002905/versions/1.0.1/file-display/task-languagelocalizer_events.json, https://openneuro.org/crn/datasets/ds000224/snapshots/00001/files/T1w_group.html, https://openneuro.org/datasets/ds003012/versions/1.0.2/file-display/participants.tsv, https://openneuro.org/crn/datasets/ds000224/snapshots/00002/files/T1w_group.html

**Content wider than screen** - (4/23/20 detected) **(MOBILE)**
ds002653 (participants.json), (11/5/20 reported files: https://openneuro.org/datasets/ds003346/versions/1.1.0/file-display/participants.tsv, https://openneuro.org/datasets/ds002134/versions/1.0.0/file-display/participants.json, https://openneuro.org/datasets/ds003114/versions/1.0.1/file-display/participants.json, https://openneuro.org/datasets/ds002411/versions/1.1.0/file-display/participants.json, https://openneuro.org/datasets/ds002738/versions/1.0.1/file-display/task-reward_events.json, https://openneuro.org/datasets/ds002940/versions/1.0.1/file-display/participants.json, https://openneuro.org/datasets/ds002905/versions/1.0.1/file-display/task-languagelocalizer_events.json, https://openneuro.org/datasets/ds003012/versions/1.0.2/file-display/participants.tsv)


**[ds001745](https://openneuro.org/datasets/ds001745/versions/1.0.0/)** (11/17 detected) flagged for the [task-StudyTest_bold](https://openneuro.org/datasets/ds001745/versions/1.0.0/file-display/task-StudyTest_bold.json) file **(MOBILE)**
- [ ] Viewport not set to "device-width"

**[ds001505](https://openneuro.org/datasets/ds001505/versions/1.0.0) - (12/29 flagged)** 
- [ ] Missing field "name"

**Server error (5xx)**
ds000245, ds001829, ds001845, ds001857, ds001995, ds000053 (snapshot 001: participants.tsv)

**Submitted URL seems to be a Soft 404**
ds000248, ds001814, ds001971, 001978

**Dataset errors**
- [ ] Invalid object type for field "publisher" (3/12: 175 items)
- [ ] Missing field "description" (3/12: 37 items)
- [ ] Invalid string length in field "description" (3/12: 24 items)
- [ ] Missing field "name" (ds001551)

**Comment by ckrountree** [comment]
ds000030, ds001784, ds000221, ds000256, ds002232,  ds000117, and ds001506 - (11/6 detected) 

3.7.1 release on 11/5 had some mobile fixes.  Perhaps, affecting these datasets???
<img width="1324" alt="ds 30" src="https://user-images.githubusercontent.com/27043528/68416761-f7ceff80-0149-11ea-9637-1b9e4dde6d61.png">
<img width="1302" alt="1784" src="https://user-images.githubusercontent.com/27043528/68416193-db7e9300-0148-11ea-9da1-b19d77bc3994.png">
![1784 v1 0 3](https://user-images.githubusercontent.com/27043528/68418149-8c3a6180-014c-11ea-8f94-2bee28dd5bdf.png)
![221](https://user-images.githubusercontent.com/27043528/68417440-4af58200-014b-11ea-8e88-863a6c119cf2.png)
![Screen Shot 2019-11-07 at 10 42 43 AM](https://user-images.githubusercontent.com/27043528/68417506-63659c80-014b-11ea-88de-f3a0b044f09c.png)
![2232](https://user-images.githubusercontent.com/27043528/68418237-ba1fa600-014c-11ea-9210-20f18a0d21fe.png)
![117](https://user-images.githubusercontent.com/27043528/68418299-d58ab100-014c-11ea-9c4f-658bc1dad17b.png)
![1506 v1 1](https://user-images.githubusercontent.com/27043528/68418338-e5a29080-014c-11ea-830e-53071eb374f4.png)
![1506 v1 2](https://user-images.githubusercontent.com/27043528/68418342-e9ceae00-014c-11ea-9004-4557dcf8dbd6.png)
