### ISSUE TITLE
Retrigger validation

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1301]
Datasets that need the validator to be retriggered for a new snapshot: (using this issue tracking datasets for retriggering validation

- [x] [ds1894](https://openneuro.org/datasets/ds001894)
~~[ds1653](https://openneuro.org/datasets/ds001653)~~
- [x] [ds30](https://openneuro.org/datasets/ds000030)
- [x] [ds1110](https://openneuro.org/datasets/ds001110)
- [x] [ds1486](https://openneuro.org/datasets/ds001486)
- [x] [ds002550](https://openneuro.org/datasets/ds002550)
- [x] [ds002294](https://openneuro.org/datasets/ds002294)
- [x] [ds224](https://openneuro.org/datasets/ds000224)

**Comment by ckrountree** [comment]
ds1894 being handled in ticket #1302

**Comment by franklin-feingold** [comment]
reopening for tracking datasets that may need to be retriggered for validation that may have been affected before the fixes to the validator

**Comment by nellh** [comment]
@franklin-feingold These are validated except for ds002294 is affected by a bids-validator bug, I'll file that and link it here.

**Comment by nellh** [comment]
Here's the [bids-validator issue affecting ds002294](https://github.com/bids-standard/bids-validator/issues/943).
