### ISSUE TITLE
Cleaning up metadata form fields

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1318]
There are a few fields that may benefit from a more descriptive title or hoovered description (similar to the hoover over description we have on our top toolbar (ie where the share dataset and publish dataset options are). These fields were originally for my internal use and can be slightly enhanced for public use. These identified may help users interpret what these fields are. ^ can be information in the hoovered description

- [x] _DOI of paper associated with DS (from submit lab)_ -> **DOI of papers from the source data lab**  (message on hover ^_Papers that were published from the Lab that collected this dataset_^)(#1466)
- [x] _DOI of paper b/c DS on OpenNeuro_ -> **Papers published from this dataset** (message on hover ^_Papers that were published from downloading this dataset_^) (#1467)
- [x] Dataset URL field may be hidden because it is now incorporated into OpenNeuro (addressed by #983)
- [x] Senior Author (message on hover ^_Please list the senior author as the last author in the dataset_description.json file field Authors_^) (#1468)
- [x] Subject ages - following Nell's suggestion (https://github.com/OpenNeuroOrg/openneuro/issues/1315)
- [x] Tasks (change from True/False to free text, perhaps this can be gathered from the validator output too) (#1469, #1473 )

CC @effigies

**Comment by ckrountree** [comment]
Is "_Dataset URL field may be hidden because it is now incorporated into OpenNeuro_" addressed sufficiently by #983?

**Comment by franklin-feingold** [comment]
Yup! I think that solution is stronger for helping the user identify the assession number
