### ISSUE TITLE
Snapshots to be generated

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1320]
this issue will be used to track datasets that are unable to have a snapshot be generated:

~~[ds1894](https://openneuro.org/datasets/ds001894) - addressed in https://github.com/OpenNeuroOrg/openneuro/issues/1319~~ [fix: 10/29]
- [x] 10/29: [ds1840](https://openneuro.org/datasets/ds001840) - same Graphql 'filter' error and behavior as https://github.com/OpenNeuroOrg/openneuro/issues/1279 (ds2181) 1/14 update: when a snapshot is tried to be generated a message immediately appears saying "This dataset does not exist." when it does
- [x] [ds002250](https://openneuro.org/datasets/ds002250) cannot generate a snapshot. Similar message to ds1840
- [x] [ds002307](https://openneuro.org/datasets/ds002307/)
- [x] [ds001019](https://openneuro.org/datasets/ds001019)
- [x] [ds002711](https://openneuro.org/datasets/ds002711) - Error 500: Internal server error from GraphQL
- [x] [ds002718](https://openneuro.org/datasets/ds002718) - Error 500: Internal server error from GraphQL
- [x] [ds002614](https://openneuro.org/datasets/ds002614)
- [x] [ds002425](https://openneuro.org/datasets/ds002425)
- [x] [ds002424](https://openneuro.org/datasets/ds002424)
