### ISSUE TITLE
Download unavailable

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1361]
This will be our tracker ticket to capture datasets that may not have a GitHub remote on our [OpenNeuroDatasets repo](https://github.com/OpenNeuroDatasets) or dataset is unavailable.

- [x] [ds000030](https://openneuro.org/datasets/ds000030)
- [x] [ds000102](https://openneuro.org/datasets/ds000102/versions/00001/) : web browser does not work. Outputs [a page](https://openneuro.org/crn/datasets/ds000102/snapshots/00001/download). Issue filled in https://github.com/OpenNeuroOrg/openneuro/issues/1396 because this is slightly different than missing GitHub remotes
- [ ] [ds000133](https://openneuro.org/datasets/ds000133) - datalad did not fetch although there is a [remote available](https://github.com/OpenNeuroDatasets/ds000133)
- [x] [ds000203](https://openneuro.org/datasets/ds000203/versions/00001)
- [ ] [ds000232](https://openneuro.org/datasets/ds000232)
- [x] [ds000244](https://openneuro.org/datasets/ds000244) - Cannot fetch data via datalad
- [x] [ds001019](https://openneuro.org/datasets/ds001019/versions/1.1.0): latest version is not downloaded via aws
- [x] [ds001107](https://openneuro.org/datasets/ds001107)
- [ ] [ds001145](https://openneuro.org/datasets/ds001145): latest version is not downloaded via aws
- [x] [ds001167](https://openneuro.org/datasets/ds001167/versions/00002)
- [x] [ds001218](https://openneuro.org/datasets/ds001218/versions/00001)
- [ ] [ds001229](https://openneuro.org/datasets/ds001229): latest version is not downloaded via aws
- [x] [ds001232](https://openneuro.org/datasets/ds001232): latest version is not downloaded via aws
- [x] [ds001233](https://openneuro.org/datasets/ds001233/versions/00003)
- [x] [ds001235](https://openneuro.org/datasets/ds001235/versions/00001)
- [ ] [ds001246](https://openneuro.org/datasets/ds001246): latest version is not downloaded via aws
- [x] [ds001371](https://openneuro.org/datasets/ds001371): dataset on aws only contains annex uuid
- [x] [ds001417](https://openneuro.org/datasets/ds001417/versions/00001)
- [x] [ds001563](https://openneuro.org/datasets/ds001563/versions/1.0.1): latest version is not downloaded via aws
- [x] [ds001583](https://openneuro.org/datasets/ds001583/versions/1.0.1): latest version is not downloaded via aws
- [ ] [ds001751](https://openneuro.org/datasets/ds001751/versions/1.0.0)
- [ ] [ds001768](https://openneuro.org/datasets/ds001768)
- [ ] [ds001796](https://openneuro.org/datasets/ds001796/versions/1.3.0)
- [ ] [ds001814](https://openneuro.org/datasets/ds001814/versions/1.0.3)
- [ ] [ds001832](https://openneuro.org/datasets/ds001832/versions/1.0.1) (discussion in [another ticket](https://github.com/OpenNeuroOrg/openneuro/issues/1310))
- [ ] [ds001838](https://openneuro.org/datasets/ds001838/versions/1.0.1)
- [ ] [ds001839](https://openneuro.org/datasets/ds001839/versions/1.0.0)
- [ ] [ds001847](https://openneuro.org/datasets/ds001847/versions/1.0.1)
- [ ] [ds001848](https://openneuro.org/datasets/ds001848/versions/1.0.1)
- [x] [ds001981](https://openneuro.org/datasets/ds001981)
- [x] [ds002041](https://openneuro.org/datasets/ds002041): latest version is not downloaded via aws
- [ ] [ds002134](https://openneuro.org/datasets/ds002134): not on aws
- [ ] [ds002158](https://openneuro.org/datasets/ds002158): not on aws
- [ ] [ds002169](https://openneuro.org/datasets/ds002169): not on aws
- [x] [ds002294](https://openneuro.org/datasets/ds002294): latest version is not downloaded via aws
- [ ] [ds002382](https://openneuro.org/datasets/ds002382): not on aws
- [ ] [ds002424](https://openneuro.org/datasets/ds002424): not on aws
- [x] [ds002311](https://openneuro.org/datasets/ds002311): latest version is not downloaded via aws
- [ ] [ds002602](https://openneuro.org/datasets/ds002602): not on aws
- [ ] [ds002606](https://openneuro.org/datasets/ds002606): not on aws
- [ ] [ds002634](https://openneuro.org/datasets/ds002634): not on aws
- [ ] [ds002647](https://openneuro.org/datasets/ds002647) and [ds002603](https://openneuro.org/datasets/ds002603) - https://neurostars.org/t/bug-in-downloading-datasets-from-openneuro/6438 - neither on aws
- [ ] [ds002672](https://openneuro.org/datasets/ds002672): not on aws
- [ ] [ds002674](https://openneuro.org/datasets/ds002674): not on aws
- [x] [ds002675](https://openneuro.org/datasets/ds002675): dataset on aws only contains annex uuid
- [x] [ds002684](https://openneuro.org/datasets/ds002684): dataset on aws only contains annex uuid

**Comment by franklin-feingold** [comment]
note: this tracking sheet is being spread out to 4 separate tickets: 
Dataset missing or latest version of dataset not on S3 or GitHub

**Comment by franklin-feingold** [comment]
closing in favor of https://github.com/OpenNeuroOrg/openneuro/issues/1649 and https://github.com/OpenNeuroOrg/openneuro/issues/1731 for S3 availability 

later, will do the analogous GitHub missing and not latest version tickets
