### ISSUE TITLE
Dataset not uptaking updates

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1381]
- [ ] [DS1796](https://openneuro.org/datasets/ds001796) is not able to update when new files are updated or added to the dataset. It appears to successfully update, but it does not render on the client-side

update (11/6): user is resuming using the webpage `resume` button. 

- [x] 12/5: another dataset is experiencing a very similar issue - [DS224](https://openneuro.org/datasets/ds000224). The user is updating files and now a particular folder is not updating and the dataset is not uptaking deleting files or folders

- [x] 2/24: [ds002152](https://openneuro.org/datasets/ds002152) is not able to delete folders or able to upload a folder

- [ ] [ds002345](https://openneuro.org/datasets/ds002345): perhaps connected with cli issues (https://github.com/OpenNeuroOrg/openneuro/issues/1515, https://neurostars.org/t/openneuro-cli-problem/5107/29?u=franklin)

- [x] [ds001486](https://openneuro.org/datasets/ds001486): is able to accept uploading a new directory but cannot delete a directory

- [x] [ds002336](https://openneuro.org/datasets/ds002336): new data cannot be uploaded to existing dataset

- [ ] [ds002385](https://openneuro.org/datasets/ds002345): unable to accept new file to resolve upload interrupted

- [ ] [ds001919](https://openneuro.org/datasets/ds001919): unable to accept new file to resolve upload interrupted

**Comment by ckrountree** [comment]
The following dataset issues have been moved to #1618:

- [ds002385](https://openneuro.org/datasets/ds002385)
- [ds001796](https://openneuro.org/datasets/ds001796)
- [ds001919](https://openneuro.org/datasets/ds001919)
- [ds002345](https://openneuro.org/datasets/ds002345)

Closing this ticket in favor of #1618.
