### ISSUE TITLE
Fixing error messages to be more human-readable

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1541]
Tracking ticket for common bugs seen that can be made to be more human-readable. I have denoted what the current error is

- [x] On the CLI  - the ServerParserError current message: https://github.com/OpenNeuroOrg/openneuro/issues/1513

- [x] Snapshot generation - current message: `Dataset does not exist.` (associated https://github.com/OpenNeuroOrg/openneuro/issues/1443) 

- [ ] Deleted dataset - current message: `GraphQL error: You do not have access to read this dataset.`

- [x] Deleting a dataset has the circle process this but then the trashcan icon returns with no message leaving the user unaware if the process was a successful

**Comment by effigies** [comment]
@franklin-feingold is the deleted dataset issue still relevant?
