### ISSUE TITLE
Datasets stuck processing update

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1618]
Datasets that have been found to not accept new data - commits may have gotten stuck

- [ ] [ds000117](https://openneuro.org/datasets/ds000117): dataset can be reset to the latest tag and we can try to process the update
- [x] [ds002385](https://openneuro.org/datasets/ds002385): unable to accept new file to resolve upload interrupted
- [x] [ds001796](https://openneuro.org/datasets/ds001796): not able to update when new files are updated or added to the dataset. It appears to successfully update, but it does not render on the client-side

update (11/6): user is resuming using the webpage `resume` button.

- [x] [ds001919](https://openneuro.org/datasets/ds001919): unable to accept new file to resolve upload interrupted
- [x] [ds002345](https://openneuro.org/datasets/ds002345): perhaps connected with cli issues (#1515, https://neurostars.org/t/openneuro-cli-problem/5107/29?u=franklin)
Dataset reuploaded ~~- [ ] [ds002394](https://openneuro.org/datasets/ds002394): attempt may have frozen the dataset page - unable to navigate to dataset landing page~~

Update 7/29: Datasets that have been found to not accept new data - commits may have gotten stuck

- [x] ds000217
- [x] ds001299
- [x] ds001894
- [x] ds002715

**Comment by ckrountree** [comment]
@nellh can you please look at ds1919.

**Comment by nellh** [comment]
ds001796 had a stuck lock from a git-annex crash at some point. Removing the lock has fixed this one.

ds002385 I think was running into some kind of limit with DataLad. We might need to break up really big commits into several to avoid this. I made many smaller commits and this worked fine.

<details>
<summary>ds002385 sample error output</summary>
FileNotInRepositoryError: command '['git', 'commit', '-m', '[DATALAD] Recorded changes', '--', 'sub-11394/ses-1/pet/sub-11394_ses-1_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11394/ses-2/anat/sub-11394_ses-2_acq-2ADNIG2_T1w.json', 'sub-11394/ses-2/anat/sub-11394_ses-2_acq-2ADNIG2_T1w.nii.gz', 'sub-11394/ses-2/pet/sub-11394_ses-2_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11394/ses-2/pet/sub-11394_ses-2_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11394/ses-2/pet/sub-11394_ses-2_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11394/ses-2/pet/sub-11394_ses-2_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11394/ses-3/anat/sub-11394_ses-3_acq-2ADNIG2_T1w.json', 'sub-11394/ses-3/anat/sub-11394_ses-3_acq-2ADNIG2_T1w.nii.gz', 'sub-11394/ses-3/pet/sub-11394_ses-3_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11394/ses-3/pet/sub-11394_ses-3_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11394/ses-3/r2prime/sub-11394_ses-3_r2prime-mag.json', 'sub-11394/ses-3/r2prime/sub-11394_ses-3_r2prime-mag.nii.gz', 'sub-11394/ses-3/r2prime/sub-11394_ses-3_r2prime-map_space-MNI152.nii.gz', 'sub-11394/ses-3/r2prime/sub-11394_ses-3_r2prime-pha.json', 'sub-11394/ses-3/r2prime/sub-11394_ses-3_r2prime-pha.nii.gz', 'sub-11395/ses-1/anat/sub-11395_ses-1_acq-1ADNIG2_T1w.json', 'sub-11395/ses-1/anat/sub-11395_ses-1_acq-1ADNIG2_T1w.nii.gz', 'sub-11395/ses-2/anat/sub-11395_ses-2_acq-1ADNIG2_T1w.json', 'sub-11395/ses-2/anat/sub-11395_ses-2_acq-1ADNIG2_T1w.nii.gz', 'sub-11403/ses-1/anat/sub-11403_ses-1_acq-1ADNIG2_T1w.json', 'sub-11403/ses-1/anat/sub-11403_ses-1_acq-1ADNIG2_T1w.nii.gz', 'sub-11403/ses-1/pet/sub-11403_ses-1_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11403/ses-1/pet/sub-11403_ses-1_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11403/ses-1/pet/sub-11403_ses-1_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11403/ses-1/pet/sub-11403_ses-1_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11403/ses-2/anat/sub-11403_ses-2_acq-2ADNIG2_T1w.json', 'sub-11403/ses-2/anat/sub-11403_ses-2_acq-2ADNIG2_T1w.nii.gz', 'sub-11403/ses-2/pet/sub-11403_ses-2_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11403/ses-2/pet/sub-11403_ses-2_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11403/ses-2/pet/sub-11403_ses-2_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11403/ses-2/pet/sub-11403_ses-2_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11405/ses-1/anat/sub-11405_ses-1_acq-1ADNIG2_T1w.json', 'sub-11405/ses-1/anat/sub-11405_ses-1_acq-1ADNIG2_T1w.nii.gz', 'sub-11405/ses-1/pet/sub-11405_ses-1_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11405/ses-1/pet/sub-11405_ses-1_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11405/ses-1/pet/sub-11405_ses-1_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11405/ses-1/pet/sub-11405_ses-1_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11405/ses-2/anat/sub-11405_ses-2_acq-2ADNIG2_T1w.json', 'sub-11405/ses-2/anat/sub-11405_ses-2_acq-2ADNIG2_T1w.nii.gz', 'sub-11405/ses-2/pet/sub-11405_ses-2_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11405/ses-2/pet/sub-11405_ses-2_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11405/ses-2/pet/sub-11405_ses-2_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11405/ses-2/pet/sub-11405_ses-2_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11409/ses-1/anat/sub-11409_ses-1_acq-1ADNIG2_T1w.json', 'sub-11409/ses-1/anat/sub-11409_ses-1_acq-1ADNIG2_T1w.nii.gz', 'sub-11409/ses-1/pet/sub-11409_ses-1_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11409/ses-1/pet/sub-11409_ses-1_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11409/ses-1/pet/sub-11409_ses-1_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11409/ses-1/pet/sub-11409_ses-1_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11409/ses-2/anat/sub-11409_ses-2_acq-2ADNIG2_T1w.json', 'sub-11409/ses-2/anat/sub-11409_ses-2_acq-2ADNIG2_T1w.nii.gz', 'sub-11409/ses-2/pet/sub-11409_ses-2_task-petfrog_acq-raclopride_pet_timecourse.nii.gz', 'sub-11409/ses-2/pet/sub-11409_ses-2_task-petfrog_acq-raclopride_pet_timecourse_space-MNI152.nii.gz', 'sub-11409/ses-2/pet/sub-11409_ses-2_task-rest_acq-dtbz_pet_bpnd.nii.gz', 'sub-11409/ses-2/pet/sub-11409_ses-2_task-rest_acq-dtbz_pet_bpnd_space-MNI152.nii.gz', 'sub-11409/ses-3/anat/sub-11409_ses-3_acq-2ADNIG2_T1w.json'
</details>

ds000117 is affected by #1662 and I think we should continue fixing datasets with missing version data in that issue since otherwise this dataset is working.

**Comment by franklin-feingold** [comment]
thank you @nellh ! sounds good!

**Comment by ckrountree** [comment]
ds000117 is now fixed.  Remaining open to check the remaining datasets.

**Comment by nellh** [comment]
I did find an issue with damaged commits in ds002715 but the most recent four here seem to behave as expected once that was resolved, can you confirm these are now fixed?
