### ISSUE TITLE
S3 git-annex only directories

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1631]
These directories have been found in our public S3 to only have a git-annex uuid in their dataset

```
ds000204
ds001371
ds002165
ds002232
ds002269
ds002385
ds002385
ds002675
ds002684
```

7/10 edit: 

- [ ] ds002425

**Comment by nellh** [comment]
First pass fixed these:
- [x] ds001371
- [x] ds002232 - S3 is now correct but GitHub rejects due to large files in the tree
- [x] ds002385
- [x] ds002675
- [x] ds002684
- [ ] ds000204 - No remotes (probably an old OpenNeuro bug that has since been fixed)
- [ ] ds002165 - No snapshots, incomplete upload?
- [ ] ds002269 - No snapshots, incomplete upload?

**Comment by nellh** [comment]
This is stale enough to close I think.
