### ISSUE TITLE
Datasets missing on S3

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1649]
**These datasets are commonly experiencing this issue:**
Datasets are not available via S3 - several of these were previously captured in https://github.com/OpenNeuroOrg/openneuro/issues/1361

**The following datasets are affected:**

- [x] ds001751
- [x] ds001768
- [x] ds001779
- [x] ds001780
- [x] ds001787
- [ ] ds001796
- [x] ds001814
- [x] ds001832 - https://github.com/OpenNeuroOrg/openneuro/issues/1310
- [x] ds001838
- [x] ds001839
- [x] ds001847
- [x] ds001848
- [x] ds002134
- [ ] ds002158
- [x] ds002169
- [x] ds002382
- [x] ds002424
- [x] ds002598
- [x] ds002602
- [x] ds002603
- [x] ds002606
- [x] ds002608
- [x] ds002634
- [x] ds002647
- [x] ds002672
- [x] ds002674
- [x] ds003061
- [x] ds003082
- [x] ds003105
- [ ] ds003838 (only contains annex uuid on S3)

**Comment by kousu** [comment]
Also

* [x] ds002900 ?:

```
$ git clone https://github.com/OpenNeuroDatasets/ds002900
$ cd ds002900
$ git annex enableremote s3-PUBLIC
enableremote s3-PUBLIC ok
(recording state in git...)
$ git annex get sub-unf
get sub-unf/anat/sub-unf_T1w.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-unf/anat/sub-unf_T2star.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-unf/anat/sub-unf_T2w.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-unf/anat/sub-unf_acq-MToff_MTS.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-unf/anat/sub-unf_acq-MTon_MTS.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-unf/anat/sub-unf_acq-T1w_MTS.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-unf/dwi/sub-unf_dwi.nii.gz (from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured
(from s3-PUBLIC...) 
  Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

  No S3 credentials configured

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	6b73241c-dfeb-4031-bfb2-2a34968683c3 -- root@openneuro-prod-dataset-worker-3:/datasets/ds002900
   	9347f9e9-9df2-46c3-8b61-836670829373 -- [s3-PUBLIC]

  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 7 failed
```

**Comment by franklin-feingold** [comment]
[ds2900 has been addressed](https://github.com/OpenNeuroOrg/openneuro/issues/1653#issuecomment-648393215)

**Comment by kousu** [comment]
Thanks for taking care of that one Franklin! It's much appreciated.

* [ ] ds002904 has only partially synced to s3:

```
$ git clone https://github.com/OpenNeuroDatasets/ds002904
Cloning into 'ds002904'...
remote: Enumerating objects: 415, done.
remote: Counting objects: 100% (415/415), done.
remote: Compressing objects: 100% (311/311), done.
remote: Total 415 (delta 9), reused 415 (delta 9), pack-reused 0
Receiving objects: 100% (415/415), 47.57 KiB | 1.25 MiB/s, done.
Resolving deltas: 100% (9/9), done.
[kousu@requiem test-julien]$ cd ds002904/
[kousu@requiem ds002904]$ ls
CHANGES  dataset_description.json  derivatives/  participants.json  participants.tsv  README  sub-ecog01/
$ git annex get .
(merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/lh.BA_exvivo.annot (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/lh.BA_exvivo.thresh.annot (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/lh.aparc.DKTatlas.annot (from s3-PUBLIC...) 

(checksum...) ok                    
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/lh.aparc.a2009s.annot (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/lh.aparc.annot (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/rh.BA_exvivo.annot (from s3-PUBLIC...) 

(checksum...) ok                      
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/rh.BA_exvivo.thresh.annot (from s3-PUBLIC...) 

(checksum...) ok                  
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/rh.aparc.DKTatlas.annot (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/rh.aparc.a2009s.annot (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/label/rh.aparc.annot (from s3-PUBLIC...) 

(checksum...) ok                    
get derivatives/freesurfer/sub-ecog01/ses-preimp/mri/T1.mgz (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/mri/aparc+aseg.mgz (from s3-PUBLIC...) 

(checksum...) ok                   
get derivatives/freesurfer/sub-ecog01/ses-preimp/mri/aparc.DKTatlas+aseg.mgz (from s3-PUBLIC...) 

(checksum...) ok                   
get derivatives/freesurfer/sub-ecog01/ses-preimp/mri/aparc.a2009s+aseg.mgz (from s3-PUBLIC...) 

(checksum...) ok                   
get derivatives/freesurfer/sub-ecog01/ses-preimp/mri/aseg.mgz (from s3-PUBLIC...) 

(checksum...) ok                   
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/lh.pial (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/lh.sphere.reg (from s3-PUBLIC...) 

(checksum...) ok                      
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/lh.thickness (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/lh.white (from s3-PUBLIC...) 

(checksum...) ok                     
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/rh.pial (from s3-PUBLIC...) 

(checksum...) ok                      
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/rh.sphere.reg (from s3-PUBLIC...) 

(checksum...) ok                      
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/rh.thickness (from s3-PUBLIC...) 

(checksum...) ok                   
get derivatives/freesurfer/sub-ecog01/ses-preimp/surf/rh.white (from s3-PUBLIC...) 

(checksum...) ok                      
get sub-ecog01/ses-postimp/anat/sub-ecog01_ses-postimp_T1w.nii.gz (from s3-PUBLIC...) 

(checksum...) ok                      
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_acq-drawing01_photo.jpg (from s3-PUBLIC...) 

(checksum...) ok                   
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_acq-drawing02_photo.jpg (from s3-PUBLIC...) 

(checksum...) ok                  
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_acq-drawing03_photo.jpg (from s3-PUBLIC...) 

(checksum...) ok                  
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_acq-render01_photo.jpg (from s3-PUBLIC...) 

(checksum...) ok                  
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_acq-render02_photo.jpg (from s3-PUBLIC...) 

(checksum...) ok                  
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_task-seizure_run-01_ieeg.eeg (from s3-PUBLIC...) 


  download failed: Forbidden


  download failed: Forbidden

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	7dc5cfa5-decb-4657-b5b2-9b6657b17382 -- [s3-PUBLIC]
   	8e4bb432-46d3-46ce-9efa-0aaac0310aa2 -- root@openneuro-prod-dataset-worker-1:/datasets/ds002904

  (Note that these git remotes have annex-ignore set: origin)
failed
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_task-seizure_run-01_ieeg.vhdr (from s3-PUBLIC...) 

(checksum...) ok                  
get sub-ecog01/ses-postimp/ieeg/sub-ecog01_ses-postimp_task-seizure_run-01_ieeg.vmrk (from s3-PUBLIC...) 

(checksum...) ok                  
get sub-ecog01/ses-postop/anat/sub-ecog01_ses-postop_T1w.nii.gz (from s3-PUBLIC...) 

(checksum...) ok                      
get sub-ecog01/ses-preimp/anat/sub-ecog01_ses-preimp_T1w.nii.gz (from s3-PUBLIC...) 

(checksum...) ok                     
(recording state in git...)
git-annex: get: 1 failed
```

**Comment by ckrountree** [comment]
See #1895 .

**Comment by nellh** [comment]
These passed the last full scan of S3 objects for datasets, closing in favor of specific issues for certain datasets.
