### ISSUE TITLE
Helpful user messages

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1736]
This tracking ticket seeks to capture and address ambiguous platform operations. These could be addressed in several different ways. 

**Useful messaging**

- [x] Clarifying `drafts` are private, while snapshots make the `drafts` data public
- [x] Clarifying the `add directories` button (e.g. what level the dataset should be selected, constraints on this option)
- [x] Confirmation message comment was posted

**Comment by ckrountree** [comment]
### SPRINT REVIEW:
Clarifying drafts are private, while snapshots make the drafts data public (top of the dataset, yellow banner):
![clarifying drafts](https://user-images.githubusercontent.com/27043528/105778173-ac586b00-5f20-11eb-9343-a578db2a8525.png)

Clarifying the `add directories` button (updates depending on which folder, see the two examples below):
![directories 1](https://user-images.githubusercontent.com/27043528/105778149-9d71b880-5f20-11eb-86b3-ec8f50fc2fb1.png)
![directories 2](https://user-images.githubusercontent.com/27043528/105778152-a1053f80-5f20-11eb-9588-ae4f86b0b8cb.png)

Confirmation message comment was posted, also includes a light gray loading progress bar:
![comment](https://user-images.githubusercontent.com/27043528/105778080-74e9be80-5f20-11eb-89f6-9e31f9b1b26b.png)
