### ISSUE TITLE
Datasets missing from GitHub

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1741]
**These datasets are commonly experiencing this issue:**
Datasets listed below do not have a GitHub repository 

**The following datasets are affected:**

- [x] ds000204
- [x] ds000232
- [x] ds001371
- [x] ds001751
- [x] ds001768
- [x] ds001779
- [x] ds001780
- [x] ds001787
- [x] ds001796
- [x] ds001814
- [x] ds001838
- [x] ds001839
- [x] ds001847
- [x] ds001848
- [x] ds001942
- [x] ds002134
- [x] ds002158
- [x] ds002169
- [x] ds002185
- [ ] [ds002232](https://github.com/OpenNeuroDatasets/ds002232)
- [x] ds002382
- [ ] [ds002385](https://github.com/OpenNeuroDatasets/ds002385)
- [x] ds002424
- [ ] [ds002425](https://github.com/OpenNeuroDatasets/ds002425)
- [x] ds002550
- [x] ds002598
- [x] ds002602
- [x] ds002603
- [x] ds002606
- [x] ds002608
- [x] ds002634
- [x] ds002647
- [x] ds002672
- [x] ds002674
- [x] ds002675
- [x] ds002684
- [x] ds002738
- [x] ds002741
- [x] [ds003592](https://github.com/OpenNeuroDatasets/ds003592)
- [x] [ds003838](https://github.com/OpenNeuroDatasets/ds003838)
- [x] [ds003999](https://github.com/OpenNeuroDatasets/ds003999)

presume these also have affected availabilities on S3
- [x] ds002761
- [x] ds002908
- [x] ds003352
- [x] ds003658 (user surfaced but dataset doesn't load)
- [x] ds003216
- [X] ds003717
- [x] ds003216

**Comment by ckrountree** [comment]
See #1895 .

**Comment by effigies** [comment]
Added ds003838 to list.

**Comment by effigies** [comment]
Added ds003999 based on https://neurostars.org/t/unable-to-get-annexed-data-from-my-just-created-publi-dataset/23000

**Comment by effigies** [comment]
Added ds003592 based on https://neurostars.org/t/unable-to-get-annexed-data-from-my-just-created-publi-dataset/23000/4

**Comment by nellh** [comment]
ds003592 and ds003999 are repaired now. ds003999 had one object at the GitHub size limit. ds003592 did not have any large objects but it would generate a pack file above GitHub's maximum size for a push (2GB) and had to be pushed incrementally to resolve it.
