### ISSUE TITLE
Sync GitHub version

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1743]
**These datasets are commonly experiencing this issue:**
These datasets do not have the latest version available on the web exported to their respective GitHub remote

**The following datasets are affected:**
*Please list below all affected datasets and add any additional information unique to that dataset. Check each off as it is resolved.*

- [x] [ds000117](https://openneuro.org/datasets/ds000117/) ([GitHub](https://github.com/OpenNeuroDatasets/ds000117))
- [ ] [ds001421](https://openneuro.org/datasets/ds001421/) ([GitHub](https://github.com/OpenNeuroDatasets/ds001421))
- [ ] ds002345 (see #1951) - history rewrite
- [ ] [ds002898](https://openneuro.org/datasets/ds002898/) ([GitHub](https://github.com/OpenNeuroDatasets/ds002898))
- [x] [ds003020](https://openneuro.org/datasets/ds003020/) ([GitHub](https://github.com/OpenNeuroDatasets/ds003020))
- [x] [ds003521](https://openneuro.org/datasets/ds003521/) ([GitHub](https://github.com/OpenNeuroDatasets/ds003521))
- [ ]  [ds003823](https://openneuro.org/datasets/ds003823/) ([GitHub](https://github.com/OpenNeuroDatasets/ds003823))
- [x] [ds004215](https://openneuro.org/datasets/ds004215/) ([GitHub](https://github.com/OpenNeuroDatasets/ds004215))

**Comment by ckrountree** [comment]
See #1895 .

**Comment by effigies** [comment]
[ds002785](https://openneuro.org/datasets/ds002785) appears to have had a `master` tag pushed to it. Deleting that from ON and GitHub is probably the main thing needed to fix things back up.

Same thing on [ds002790](https://openneuro.org/datasets/ds002790).

**Comment by effigies** [comment]
Added [ds000117](https://openneuro.org/datasets/ds000117/). A new snapshot ([1.0.4](https://openneuro.org/datasets/ds000117/versions/1.0.4)) was made on 2020.12.18, but it was not synced to GitHub, so this is a live issue, not just a matter of re-exporting.

**Comment by ckrountree** [comment]
@nellh let's get the fix for ds002785 and ds002790 in this release 3.27.

**Comment by nellh** [comment]
> @nellh let's get the fix for ds002785 and ds002790 in this release 3.27.

This is resolved except for ds002345 which requires some history changes to be repaired. https://github.com/OpenNeuroOrg/openneuro/issues/1951 tracks that issue.

**Comment by ckrountree** [comment]
@effigies did you ever confirm if it is okay to rewrite the history to replace those wave files with annexed copies of them to make available on GitHub?

**Comment by effigies** [comment]
Yes. Conversation on #1951.

**Comment by effigies** [comment]
Unchecked ds000117. Made an edit today and it does not seem to have propagated to GitHub.

**Comment by effigies** [comment]
Added ds003949 to list.

**Comment by nellh** [comment]
Looks like ds000117 failed because it got stuck unexporting the same file indefinitely. I reran it a few times it looks like that worked. It stills fails to unexport these files when re-exporting the snapshot despite all the content being in the S3 bucket. Going to retest it after the planned git-annex update and will drop/re-export the S3 content from scratch if this is still happening.
```
unexport s3-PUBLIC .git-annex-tmp-content-MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.bmp ok
unexport s3-PUBLIC .git-annex-tmp-content-MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.bmp ok
unexport s3-PUBLIC .git-annex-tmp-content-MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.bmp ok
unexport s3-PUBLIC .git-annex-tmp-content-MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.bmp ok
unexport s3-PUBLIC .git-annex-tmp-content-MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.bmp ok
unexport s3-PUBLIC .git-annex-tmp-content-MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.bmp ok
```

ds003949 was caused by the issues fixed in release 4.3.0. It's running now and should be available soon.

**Comment by effigies** [comment]
Added ds003505. Tried to re-export this morning and hasn't hit yet. Might just be impatient, though.

**Comment by nellh** [comment]
> Added ds003505. Tried to re-export this morning and hasn't hit yet. Might just be impatient, though.

I just checked and it looks like it is available. Was it just missing 1.1.1?

**Comment by effigies** [comment]
Yeah, 1.1.1 just uploaded, but master still hasn't updated. `git-annex` branch is at least recent, but I haven't tried fetching all the data from 1.1.1.

**Comment by effigies** [comment]
ds001421@master is at v1.2.1, but the latest pushed tag is 1.0.0. A couple tags in the last couple days, and neither master nor tags were updated.

**Comment by adswa** [comment]
Hi, I hope you don't mind me piling on top of this. As I saw ds004078 mentioned in the list above, I wanted to link/migrate https://github.com/datalad-handbook/book/issues/864 here. It seems that ds004078 has not received updates to versions 1.0.2 and the most recent 1.0.3. Thanks much, and please let me know if there is a better place to raise this. :) 
cc @kingjr

**Comment by effigies** [comment]
Thanks @adswa! I should also note that I added ds002898 yesterday.

**Comment by effigies** [comment]
Added ds002578.

**Comment by effigies** [comment]
Added ds004212, which was the subject of https://github.com/OpenNeuroOrg/openneuro/issues/2748. Here, it seems main is not synced, although 2.0.0 was pushed, and not all files are retrievable via datalad. Errors like

```
get(error): derivatives/preprocessed/P1_cosmofile.mat (file) [download failed: Forbidden
unknown export location
```

**Comment by nellh** [comment]
ds004212 is exported correctly now.

**Comment by effigies** [comment]
Thanks, Nell!

**Comment by effigies** [comment]
ds004215 is also behind. Master is at 1.0.0, but 1.0.2 exists.

**Comment by effigies** [comment]
ds003823 is available through datalad if you checkout the latest snapshot. Apparently there are issues downloading through CLI, but I assume syncing so that `main` is up-to-date on GitHub will probably resolve everything else.

**Comment by effigies** [comment]
Added ds003521, xref freshdesk issue 1532. `master`/`main` is at 2.1.0, OpenNeuro is at 2.2.0.

**Comment by effigies** [comment]
I've removed all completed entries and verified that unchecked entries are still open.

**Comment by nellh** [comment]
> Added ds003521, xref freshdesk issue 1532. `master`/`main` is at 2.1.0, OpenNeuro is at 2.2.0.

This one is fixed. Cause was the unversioned objects issue, replacing the damaged objects fixed this and should allow future exports.

**Comment by effigies** [comment]
@nellh I have pushed `1.0.2` to `main` on https://github.com/OpenNeuroDatasets/ds004215, since it looks like there was only one annexed file changed in that delta, and I was able to `git annex get` it. I ran `git annex fsck` and everything looks okay. Is there anything else to do to verify that everything's good?

**Comment by nellh** [comment]
> @nellh I have pushed `1.0.2` to `main` on https://github.com/OpenNeuroDatasets/ds004215, since it looks like there was only one annexed file changed in that delta, and I was able to `git annex get` it. I ran `git annex fsck` and everything looks okay. Is there anything else to do to verify that everything's good?

That should be it. I just double checked it and it looks good to me.

**Comment by effigies** [comment]
Added ds003020. Looks like it got some files stuck in git instead of git-annex, but only during intermittent commits. The tags are all clean:

```console
❯ for REF in $(git tag); do echo -n "$REF: "; git ls-tree -r --format='%(objectsize) %(path)' $REF | sort -n | tail -n 1; done
1.0.0: 1272 task-MotorLocalizer_bold.json
1.0.1: 1272 task-MotorLocalizer_bold.json
1.0.2: 1272 task-MotorLocalizer_bold.json
1.0.3: 1272 task-MotorLocalizer_bold.json
1.0.4: 1272 task-MotorLocalizer_bold.json
1.0.5: 1272 task-MotorLocalizer_bold.json
1.0.6: 1272 task-MotorLocalizer_bold.json
1.0.7: 1272 task-MotorLocalizer_bold.json
1.1.0: 1723 README
1.1.1: 1723 README
2.0.0: 2005 derivative/respdict.json
2.0.1: 2005 derivative/respdict.json
2.0.2: 2005 derivative/respdict.json
```

**Comment by effigies** [comment]
@nellh Sorry to bug, but is there anything I can do for ds003020, or will you need to? I think this is essentially the same problem as ds002345.

**Comment by nellh** [comment]
> @nellh Sorry to bug, but is there anything I can do for ds003020, or will you need to? I think this is essentially the same problem as ds002345.

It's fixed now, I rewrote the repo history to remove those large files from git.

**Comment by nellh** [comment]
This is out of date and now resolved I believe.
