### ISSUE TITLE
Empty github repositories for datasets

### ISSUE THREAD

**Issue by surchs** [OpenNeuroOrg/openneuro#3037]
### Dataset issue

The following datasets have repositories on https://github.com/OpenNeuroDatasets/ that are empty.
As far as I can tell, these all exist on openneuro.org as real datasets.

### The following datasets are affected

- [ ] https://github.com/OpenNeuroDatasets/ds002232 and ->  https://openneuro.org/datasets/ds002232 
- [ ] https://github.com/OpenNeuroDatasets/ds002385 and ->  https://openneuro.org/datasets/ds002385
- [ ] https://github.com/OpenNeuroDatasets/ds002425 and ->  https://openneuro.org/datasets/ds002425
- [ ] https://github.com/OpenNeuroDatasets/ds003052 and ->  https://openneuro.org/datasets/ds003052
- [ ] https://github.com/OpenNeuroDatasets/ds003367 and ->  https://openneuro.org/datasets/ds003367
- [ ] https://github.com/OpenNeuroDatasets/ds003396 and ->  https://openneuro.org/datasets/ds003396
- [ ] https://github.com/OpenNeuroDatasets/ds003484 and ->  https://openneuro.org/datasets/ds003484
- [ ] https://github.com/OpenNeuroDatasets/ds003508 and ->  https://openneuro.org/datasets/ds003508
- [ ] https://github.com/OpenNeuroDatasets/ds004495 and ->  https://openneuro.org/datasets/ds004495
- [ ] https://github.com/OpenNeuroDatasets/ds004630 and ->  https://openneuro.org/datasets/ds004630
- [ ] https://github.com/OpenNeuroDatasets/ds004892 and ->  https://openneuro.org/datasets/ds004892
- [ ] https://github.com/OpenNeuroDatasets/ds005016 and ->  https://openneuro.org/datasets/ds005016

**Comment by MontrealSergiy** [comment]
Even more often, if dataset present, one or even few more recent versions/snapshots are missing from GitHub. For example ds003194 version 1.0.4  , version 1.1.4 of ds002345

**Comment by effigies** [comment]
Done

**Comment by yarikoptic** [comment]
I wondered on what is "Done" exactly means here since there is still empty https://github.com/OpenNeuroDatasets/ds003396

**Comment by effigies** [comment]
https://github.com/OpenNeuroDatasets/ds003396 has now been deleted. https://openneuro.org/datasets/ds003396 indicates that the dataset was removed from OpenNeuro for subject privacy reasons.

The other datasets are synced. We have a script (https://github.com/OpenNeuroOrg/openneuro/blob/master/scripts/check-github-sync) that we use to check the correspondence between the GraphQL API (matches all public datasets, findable via search) and GitHub.
