### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3157]
### Dataset issue

A user reported the following files cannot be opened. This issue is to track investigation and resolution.

<details><summary>Details</summary>
<p>

```
ds001241/sub-23/anat/._sub-23_T1w.nii.gz
ds003059/sub-001/anat/._sub-001_T1w.nii.gz
ds003059/sub-002/anat/._sub-002_T1w.nii.gz
ds003059/sub-003/anat/._sub-003_T1w.nii.gz
ds003059/sub-004/anat/._sub-004_T1w.nii.gz
ds003059/sub-006/anat/._sub-006_T1w.nii.gz
ds003059/sub-009/anat/._sub-009_T1w.nii.gz
ds003059/sub-010/anat/._sub-010_T1w.nii.gz
ds003059/sub-011/anat/._sub-011_T1w.nii.gz
ds003059/sub-012/anat/._sub-012_T1w.nii.gz
ds003059/sub-013/anat/._sub-013_T1w.nii.gz
ds003059/sub-015/anat/._sub-015_T1w.nii.gz
ds003059/sub-017/anat/._sub-017_T1w.nii.gz
ds003059/sub-018/anat/._sub-018_T1w.nii.gz
ds003059/sub-019/anat/._sub-019_T1w.nii.gz
ds003059/sub-020/anat/._sub-020_T1w.nii.gz
ds002295/sub-03/ses-anat/anat/sub-03_ses-anat_acq-memp2rage_inv-1_part-mag_MPRAGE.nii.gz
ds002311/sub-02/anat/sub-02_T1w.nii.gz
ds002311/sub-16/anat/sub-16_T1w.nii.gz
ds004146/sub-0162/ses-02/anat/sub-0162_ses-02_UNIT1_denoised.nii.gz
ds002674/sub-01/ses-07/anat/sub-01_ses-07_T2star.nii.gz
ds003707/sub-33/anat/sub-33_T1w.nii.gz
ds003707/sub-33/anat/sub-33_T2w.nii.gz
ds004217/sub-011/anat/sub-011_T1w.nii.gz
ds004217/sub-014/anat/sub-014_T1w.nii.gz
ds004217/sub-018/anat/sub-018_T1w.nii.gz
ds004217/sub-025/anat/sub-025_T1w.nii.gz
ds004217/sub-064/anat/sub-064_T1w.nii.gz
ds004217/sub-070/anat/sub-070_T1w.nii.gz
ds004217/sub-071/anat/sub-071_T1w.nii.gz
ds004217/sub-074/anat/sub-074_T1w.nii.gz
ds004217/sub-077/anat/sub-077_T1w.nii.gz
ds004217/sub-082/anat/sub-082_T1w.nii.gz
ds004217/sub-083/anat/sub-083_T1w.nii.gz
ds004217/sub-084/anat/sub-084_T1w.nii.gz
ds004217/sub-085/anat/sub-085_T1w.nii.gz
ds004217/sub-090/anat/sub-090_T1w.nii.gz
ds004261/sub-2062/ses-day1PM/anat/sub-2062_ses-day1PM_T1w.nii.gz
ds004349/sub-67/anat/sub-67_T1w.nii.gz
ds004349/sub-67/anat/sub-67_T2w.nii.gz
ds004406/sub-02/ses-01/anat/sub-02_ses-01_T1w.nii.gz
ds004406/sub-08/ses-01/anat/sub-08_ses-01_T1w.nii.gz
ds004406/sub-10/ses-01/anat/sub-10_ses-01_T1w.nii.gz
ds004406/sub-17/ses-01/anat/sub-17_ses-01_T1w.nii.gz
ds004406/sub-18/ses-01/anat/sub-18_ses-01_T1w.nii.gz
ds004406/sub-25/ses-01/anat/sub-25_ses-01_T1w.nii.gz
ds004443/sub-0903/ses-01/anat/sub-0903_ses-01_T1w.nii.gz
ds004443/sub-0903/ses-01/anat/sub-0903_ses-01_T2w.nii.gz
ds004482/sub-16/anat/sub-16_T1w.nii.gz
```

</p>
</details> 

### The following datasets are affected

* [ ] ds001241 - `._` prefixes, probably just need deleting and re-releasing
* [ ] ds003059 - `._` prefixes, probably just need deleting and re-releasing
* [ ] ds002295 - `sub-03/ses-anat/anat/sub-03_ses-anat_acq-memp2rage_inv-1_part-mag_MPRAGE.nii.gz`
* [ ] ds002311 - Some T1w images
* [ ] ds004146 - `_UNIT1_denoised` :-/
* [ ] ds002674 - T2star
* [ ] ds003707 - Two anatomicals
* [ ] ds004217 - Several T1w images
* [ ] ds004261 - One T1w
* [ ] ds004349 - Two anatomicals
* [ ] ds004406 - Several T1w images
* [ ] ds004443 - Two anatomicals
* [ ] ds004482 - One T1w

**Comment by effigies** [comment]
ds002345:

```
root@openneuro-prod-dataset-worker-1:/datasets/ds002345# git annex list | grep -v ^X
here
|github
||s3-PRIVATE
|||s3-PUBLIC
||||web
|||||bittorrent
||||||
___X__ stimuli/santa_audio.wav
___X__ stimuli/shapessocial_audio.wav
___X__ stimuli/sherlock_audio.wav
___X__ stimuli/tunnel_audio.wav
___X__ stimuli/upintheair_audio.wav
___X__ sub-007/func/sub-007_task-pieman_bold.nii.gz
___X__ sub-010/func/sub-010_task-pieman_run-1_bold.nii.gz
___X__ sub-013/func/sub-013_task-pieman_run-2_bold.nii.gz
___X__ sub-017/func/sub-017_task-pieman_bold.nii.gz
___X__ sub-018/anat/sub-018_T1w.nii.gz
___X__ sub-019/anat/sub-019_T1w.nii.gz
___X__ sub-021/anat/sub-021_T1w.nii.gz
___X__ sub-022/anat/sub-022_T1w.nii.gz
```

@snastase Is there any chance you have the original files for these to re-upload?

**Comment by snastase** [comment]
Hey @effigies, I just went through and "updated" each of these with the original files through the browser interface on OpenNeuro—do they seem normal now?

**Comment by effigies** [comment]
@snastase Still seeing these ones missing:

```
root@openneuro-prod-dataset-worker-1:/datasets/ds002345# git annex list | grep -v ^X
here
|github
||s3-PRIVATE
|||s3-PUBLIC
||||web
|||||bittorrent
||||||
___X__ sub-007/func/sub-007_task-pieman_bold.nii.gz
___X__ sub-010/func/sub-010_task-pieman_run-1_bold.nii.gz
___X__ sub-017/func/sub-017_task-pieman_bold.nii.gz
___X__ sub-018/anat/sub-018_T1w.nii.gz
___X__ sub-019/anat/sub-019_T1w.nii.gz
```

**Comment by snastase** [comment]
Hmm okay I tried re-uploading the files more  s l o w l y

Did they stick this time? I see the validator error count going down, but there may be other issues.

**Comment by effigies** [comment]
Looks better. I think some NIfTIs got uploaded as JSON files instead. I'm going to try to revert those...

**Comment by effigies** [comment]
Okay, the JSON files are reverted. The main complaint now is that there are TRs in the NIfTI headers that don't match the `RepetitionTime` metadata.

```
root@openneuro-prod-dataset-worker-1:/datasets/ds002345# nib-ls sub-*/func/*_bold.nii.gz | grep -v 'x1.5'
sub-002/func/sub-002_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-002/func/sub-002_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-003/func/sub-003_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-003/func/sub-003_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-004/func/sub-004_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-004/func/sub-004_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-005/func/sub-005_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-005/func/sub-005_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-009/func/sub-009_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-010/func/sub-010_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-010/func/sub-010_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-011/func/sub-011_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-011/func/sub-011_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-012/func/sub-012_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-012/func/sub-012_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-013/func/sub-013_task-pieman_run-1_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-013/func/sub-013_task-pieman_run-2_bold.nii.gz         int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-017/func/sub-017_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-018/func/sub-018_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-019/func/sub-019_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-020/func/sub-020_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-021/func/sub-021_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-022/func/sub-022_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-023/func/sub-023_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-024/func/sub-024_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-025/func/sub-025_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-027/func/sub-027_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-028/func/sub-028_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-029/func/sub-029_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-030/func/sub-030_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-031/func/sub-031_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-032/func/sub-032_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-033/func/sub-033_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-034/func/sub-034_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-035/func/sub-035_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-036/func/sub-036_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-037/func/sub-037_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-038/func/sub-038_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-039/func/sub-039_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-040/func/sub-040_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-042/func/sub-042_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-043/func/sub-043_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-044/func/sub-044_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-045/func/sub-045_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-046/func/sub-046_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-047/func/sub-047_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-048/func/sub-048_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-049/func/sub-049_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-050/func/sub-050_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
sub-051/func/sub-051_task-pieman_bold.nii.gz               int16 [ 64,  64,  27, 300]  3.00x3.00x4.00x1500.00   sform
```

**Comment by effigies** [comment]
That said, those files do also claim their units are `('mm', 'msec')`, so this is a validator error. I suppose you can either rewrite the files to use seconds, or we can patch the validator.

Update: https://github.com/bids-standard/bids-specification/pull/2170 resolves these errors.
