### ISSUE TITLE
Incompletely deleted datasets (including failed redirects)

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3183]
This issue is for tracking datasets that have been incompletely deleted as well as redirects have failed to be put into place.

- [ ] https://openneuro.org/datasets/ds005575 should redirect to https://openneuro.org/datasets/ds005594
    - [ ] Fully deleted
- [ ] https://openneuro.org/datasets/ds003419 should redirect to https://openneuro.org/datasets/ds003799
    - [ ] Not deleted on server
    - [ ] https://github.com/OpenNeuroDatasets/ds003419 was not deleted
