### ISSUE TITLE
Data set page design review

### ISSUE THREAD

**Issue by Xesme** [OpenNeuroOrg/openneuro#341]

**Comment by nellh** [comment]
Refocused #317 to focus on the overall dataset/snapshot page and UI along with how to integrate comments into the page (#328).

**Comment by nellh** [comment]
We should also look at how the dataset pages are indexed by search engines and if any changes to the page could improve that.

**Comment by Xesme** [comment]
The dataset page has been reviewed. Additional notes will be added after a more in depth review of the analysis panel tomorrow. 

Please note these are not 'high quality' design comps. The bare minimum styling has been added. 

A few things to be added: 
- [ ] **A follow button** next to the title needs to be added in order to implement issue #337 Follow Dataset Feature. 
- [ ] **A comments section** will be added below the digital documents #328 Dataset Comments. Comments will default to the dataset and not versioning, but we will use an in reference to version tag.
- [ ] **Dataset file tree** 1. tweaks to the spacing and padding for improved visual design 2. download and view buttons will be available from an onClick event. 
 
- [ ] (  🚩 @chrisfilo )  **Embedded twitter timeline** this has not been added to the design comp, just for clarification on ticket #338: you would like a twitter timeline to be embedded on the dataset page in order to view the tweet history for each specific dataset? 


![screen shot 2018-01-18 at 1 38 06 pm](https://user-images.githubusercontent.com/24839005/35126105-fe9c4038-fc60-11e7-801d-c0e6c700ff7d.png)
![screen shot 2018-01-18 at 2 05 18 pm](https://user-images.githubusercontent.com/24839005/35126112-0164b41c-fc61-11e7-94d6-89908111dfb4.png)
![screen shot 2018-01-18 at 1 25 11 pm](https://user-images.githubusercontent.com/24839005/35126114-030c3128-fc61-11e7-89c8-0f739dbaebe4.png)

**Comment by chrisgorgo** [comment]
@Xesme yes.

Also please make sure one will be able to link to individual comments via `#`. Thanks!
